// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-qu-NZwpJ72cW5Yo_ahyPW0l04Ns_BM',
    appId: '1:796972180628:web:bcbbf89217d410d4048081',
    messagingSenderId: '796972180628',
    projectId: 'flutter-crud-firebase-911ad',
    authDomain: 'flutter-crud-firebase-911ad.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-911ad.firebasestorage.app',
    measurementId: 'G-2GSVXDKMCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuVvzkIEHz0YLtL0ohhU13d6zmKZ0mW2w',
    appId: '1:796972180628:android:f64d992d4965a12b048081',
    messagingSenderId: '796972180628',
    projectId: 'flutter-crud-firebase-911ad',
    storageBucket: 'flutter-crud-firebase-911ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyYGN1iPz10OAEvtzLWNgtMJQCtiISXA',
    appId: '1:796972180628:ios:b25521059021d076048081',
    messagingSenderId: '796972180628',
    projectId: 'flutter-crud-firebase-911ad',
    storageBucket: 'flutter-crud-firebase-911ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyYGN1iPz10OAEvtzLWNgtMJQCtiISXA',
    appId: '1:796972180628:ios:b25521059021d076048081',
    messagingSenderId: '796972180628',
    projectId: 'flutter-crud-firebase-911ad',
    storageBucket: 'flutter-crud-firebase-911ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz-qu-NZwpJ72cW5Yo_ahyPW0l04Ns_BM',
    appId: '1:796972180628:web:0da9827d37e0380f048081',
    messagingSenderId: '796972180628',
    projectId: 'flutter-crud-firebase-911ad',
    authDomain: 'flutter-crud-firebase-911ad.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-911ad.firebasestorage.app',
    measurementId: 'G-6ZZD0LREKK',
  );

}